### ISSUE TITLE
Minigames connect with friend issue

### ISSUE THREAD

**Issue by Lukasek29** [ReHamster/AlcatrazServer#14]
Hi, I can invite my friend to freeroam and drive but I can't play minigames with my friend via RadminVPN and I don't know why. I was using ***redacted*** BTW

**Comment by SoapyMan** [comment]
Unfortunately more than one players can't be in the same network exposing same port to the Driver Madness-hosted Alcatraz server. You need to host own server

**Comment by Lukasek29** [comment]
I used own server, and we're using RadminVPN, even local network doesn't
work.

**Comment by SoapyMan** [comment]
You might not need a VPN and connect directly to your local hosted server or server must be included in VPN

**Comment by Lukasek29** [comment]
I tried even connect via localhost, my friend can join to me to room and
drive  but we can't play a minigames because of connection error then we'll
be back on the freedrive even when we're searching match but we'll alone on
the lobby/match on my own server, I have set ip adress and sandboxkey, BTW
i'm using this folder http s://www. mediaf ire.com/folder/xvqr0
1lbtd0kq/DriverSF to be sure what kind of server i'm using, if I supposed
to use server from GitHub so I'll download and try to figure out how to
start it, and I'm so sorry if I described it badly or I didn't understand.

**Comment by SoapyMan** [comment]
Oh, now I get it, you've ran into game error. Game does not allow player IDs less than 1000. You need make a fresh database and create players starting with ID=1000 or you need to build Alcatraz with latest changes (it fixes this bug)

**Comment by Lukasek29** [comment]
And how to create player starting with ID=1000?

**Comment by Lukasek29** [comment]
And how to create player starting with ID=1000? please. And do you know on
AlcatrazServer from githup is database and in there are exposed password of
players?

**Comment by Lukasek29** [comment]
I found out how to do that, I used DB Browser. Thank you for helping me to understand why it doesn't work, I appreciate it.
